using NUnit.Framework;
using TestsGeneratorLib;

namespace TestsGeneratorLib.Tests;

[TestFixture]
public class TestCodeGeneratorTests
{
    private const string SimpleClassSource = @"
namespace MyCode
{
    public class MyClass
    {
        public void FirstMethod() { }
        public void SecondMethod() { }
    }
}";

    private const string OverloadedMethodsSource = @"
namespace MyCode
{
    public class Calculator
    {
        public int Add(int a, int b) { return a + b; }
        public double Add(double a, double b) { return a + b; }
    }
}";

    private const string MultipleClassesSource = @"
namespace MyCode
{
    public class Foo
    {
        public void DoFoo() { }
    }

    public class Bar
    {
        public void DoBar() { }
    }
}";

    private const string DependencyInjectionSource = @"
namespace MyCode
{
    public class MyService
    {
        public MyService(IRepository repository, ILogger logger)
        {
        }

        public int Calculate(int x) { return x; }
        public void Process() { }
    }
}";

    private const string ReturnTypeSource = @"
namespace MyCode
{
    public class Converter
    {
        public string Convert(int value) { return value.ToString(); }
        public int Parse(string text) { return int.Parse(text); }
        public void DoNothing() { }
    }
}";

    [Test]
    public void Generate_SimpleClass_ReturnsOneTestClass()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result.Count, Is.EqualTo(1));
        Assert.That(result[0].FileName, Is.EqualTo("MyClassTests.cs"));
    }

    [Test]
    public void Generate_SimpleClass_ContainsTestFixtureAttribute()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("[TestFixture]"));
    }

    [Test]
    public void Generate_SimpleClass_ContainsTestMethods()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("FirstMethodTest"));
        Assert.That(result[0].Content, Does.Contain("SecondMethodTest"));
    }

    [Test]
    public void Generate_SimpleClass_ContainsAssertFail()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }

    [Test]
    public void Generate_OverloadedMethods_NumbersMethodNames()
    {
        var result = TestCodeGenerator.Generate(OverloadedMethodsSource);

        Assert.That(result[0].Content, Does.Contain("Add1Test"));
        Assert.That(result[0].Content, Does.Contain("Add2Test"));
    }

    [Test]
    public void Generate_MultipleClasses_ReturnsSeparateTestClasses()
    {
        var result = TestCodeGenerator.Generate(MultipleClassesSource);

        Assert.That(result.Count, Is.EqualTo(2));
        Assert.That(result.Any(r => r.FileName == "FooTests.cs"), Is.True);
        Assert.That(result.Any(r => r.FileName == "BarTests.cs"), Is.True);
    }

    [Test]
    public void Generate_WithDependencies_ContainsMockFields()
    {
        var result = TestCodeGenerator.Generate(DependencyInjectionSource);
        var content = result[0].Content;

        Assert.That(content, Does.Contain("Mock<IRepository>"));
        Assert.That(content, Does.Contain("Mock<ILogger>"));
    }

    [Test]
    public void Generate_WithDependencies_ContainsSetUp()
    {
        var result = TestCodeGenerator.Generate(DependencyInjectionSource);
        var content = result[0].Content;

        Assert.That(content, Does.Contain("[SetUp]"));
        Assert.That(content, Does.Contain("SetUp()"));
    }

    [Test]
    public void Generate_WithDependencies_ContainsMoqUsing()
    {
        var result = TestCodeGenerator.Generate(DependencyInjectionSource);

        Assert.That(result[0].Content, Does.Contain("using Moq;"));
    }

    [Test]
    public void Generate_ReturnTypeMethod_ContainsActualAndExpected()
    {
        var result = TestCodeGenerator.Generate(ReturnTypeSource);
        var content = result[0].Content;

        Assert.That(content, Does.Contain("string actual"));
        Assert.That(content, Does.Contain("string expected"));
        Assert.That(content, Does.Contain("int actual"));
        Assert.That(content, Does.Contain("int expected"));
    }

    [Test]
    public void Generate_ReturnTypeMethod_ContainsAssertThat()
    {
        var result = TestCodeGenerator.Generate(ReturnTypeSource);

        Assert.That(result[0].Content, Does.Contain("Assert.That(actual, Is.EqualTo(expected))"));
    }

    [Test]
    public void Generate_VoidMethod_CallsMethodWithoutCapture()
    {
        var result = TestCodeGenerator.Generate(ReturnTypeSource);
        var content = result[0].Content;

        Assert.That(content, Does.Contain("DoNothingTest"));
    }

    [Test]
    public void Generate_CorrectTestNamespace()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("namespace MyCode.Tests"));
    }

    [Test]
    public void Generate_MethodWithParams_ContainsArrangeVariables()
    {
        var result = TestCodeGenerator.Generate(OverloadedMethodsSource);
        var content = result[0].Content;

        Assert.That(content, Does.Contain("int a = 0"));
        Assert.That(content, Does.Contain("int b = 0"));
    }

    [Test]
    public void Generate_ContainsNUnitUsing()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("using NUnit.Framework;"));
    }

    [Test]
    public void Generate_ContainsOriginalNamespaceUsing()
    {
        var result = TestCodeGenerator.Generate(SimpleClassSource);

        Assert.That(result[0].Content, Does.Contain("using MyCode;"));
    }
}
