using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TestsGeneratorLib;

public static class TestCodeGenerator
{
    private static readonly Dictionary<string, string> DefaultValues = new()
    {
        { "int", "0" },
        { "Int32", "0" },
        { "long", "0L" },
        { "Int64", "0L" },
        { "short", "0" },
        { "Int16", "0" },
        { "byte", "0" },
        { "Byte", "0" },
        { "float", "0f" },
        { "Single", "0f" },
        { "double", "0.0" },
        { "Double", "0.0" },
        { "decimal", "0m" },
        { "Decimal", "0m" },
        { "bool", "false" },
        { "Boolean", "false" },
        { "char", "'\\0'" },
        { "Char", "'\\0'" },
        { "string", "\"\"" },
        { "String", "\"\"" },
    };

    public static List<TestClassInfo> Generate(string sourceCode)
    {
        var tree = CSharpSyntaxTree.ParseText(sourceCode);
        var root = tree.GetCompilationUnitRoot();
        var result = new List<TestClassInfo>();

        var classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.Modifiers.Any(SyntaxKind.PublicKeyword));

        foreach (var classDecl in classes)
        {
            var namespaceName = GetNamespace(classDecl);
            var testNamespace = namespaceName != null ? namespaceName + ".Tests" : "Tests";
            var className = classDecl.Identifier.Text;
            var testClassName = className + "Tests";

            var constructorInfo = AnalyzeConstructor(classDecl);
            var methods = classDecl.Members.OfType<MethodDeclarationSyntax>()
                .Where(m => m.Modifiers.Any(SyntaxKind.PublicKeyword))
                .ToList();

            var methodNames = ResolveMethodNames(methods);
            var testMethods = new List<MemberDeclarationSyntax>();

            var fields = new List<MemberDeclarationSyntax>();
            var setupStatements = new List<StatementSyntax>();

            var fieldName = "_" + char.ToLower(className[0]) + className.Substring(1) + "UnderTest";

            fields.Add(ParseMemberDeclaration(
                $"private {className} {fieldName};")!);

            foreach (var dep in constructorInfo.InterfaceDependencies)
            {
                fields.Add(ParseMemberDeclaration(
                    $"private Mock<{dep.Type}> {dep.FieldName};")!);
                setupStatements.Add(ParseStatement(
                    $"{dep.FieldName} = new Mock<{dep.Type}>();"));
            }

            var ctorArgs = string.Join(", ",
                constructorInfo.AllParameters.Select(p =>
                    constructorInfo.InterfaceDependencies.Any(d => d.ParameterName == p.Name)
                        ? constructorInfo.InterfaceDependencies.First(d => d.ParameterName == p.Name).FieldName + ".Object"
                        : GetDefaultValueExpression(p.Type)));

            setupStatements.Add(ParseStatement(
                $"{fieldName} = new {className}({ctorArgs});"));

            var setupMethod = MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "SetUp")
                .AddModifiers(Token(SyntaxKind.PublicKeyword))
                .AddAttributeLists(AttributeList(SingletonSeparatedList(Attribute(IdentifierName("SetUp")))))
                .WithBody(Block(setupStatements));

            for (int i = 0; i < methods.Count; i++)
            {
                var method = methods[i];
                var testMethodName = methodNames[i];
                var statements = new List<StatementSyntax>();

                var parameters = method.ParameterList.Parameters;
                var paramVarNames = new List<string>();

                foreach (var param in parameters)
                {
                    var paramType = param.Type?.ToString() ?? "object";
                    var paramName = param.Identifier.Text;
                    paramVarNames.Add(paramName);
                    var defaultVal = GetDefaultValueExpression(paramType);
                    statements.Add(ParseStatement($"{paramType} {paramName} = {defaultVal};"));
                }

                var returnType = method.ReturnType.ToString();
                var argsString = string.Join(", ", paramVarNames);
                var methodCall = $"{fieldName}.{method.Identifier.Text}({argsString})";

                if (returnType == "void")
                {
                    statements.Add(ParseStatement($"{methodCall};"));
                    statements.Add(ParseStatement("Assert.Fail(\"autogenerated\");"));
                }
                else
                {
                    statements.Add(ParseStatement($"{returnType} actual = {methodCall};"));
                    var expectedDefault = GetDefaultValueExpression(returnType);
                    statements.Add(ParseStatement($"{returnType} expected = {expectedDefault};"));
                    statements.Add(ParseStatement("Assert.That(actual, Is.EqualTo(expected));"));
                    statements.Add(ParseStatement("Assert.Fail(\"autogenerated\");"));
                }

                var testMethod = MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), testMethodName)
                    .AddModifiers(Token(SyntaxKind.PublicKeyword))
                    .AddAttributeLists(AttributeList(SingletonSeparatedList(Attribute(IdentifierName("Test")))))
                    .WithBody(Block(statements));

                testMethods.Add(testMethod);
            }

            if (methods.Count == 0)
            {
                var failMethod = MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "DefaultTest")
                    .AddModifiers(Token(SyntaxKind.PublicKeyword))
                    .AddAttributeLists(AttributeList(SingletonSeparatedList(Attribute(IdentifierName("Test")))))
                    .WithBody(Block(ParseStatement("Assert.Fail(\"autogenerated\");")));
                testMethods.Add(failMethod);
            }

            var members = new List<MemberDeclarationSyntax>();
            members.AddRange(fields);
            members.Add(setupMethod);
            members.AddRange(testMethods);

            var testClass = ClassDeclaration(testClassName)
                .AddModifiers(Token(SyntaxKind.PublicKeyword))
                .AddAttributeLists(AttributeList(SingletonSeparatedList(Attribute(IdentifierName("TestFixture")))))
                .AddMembers(members.ToArray());

            var namespaceDecl = NamespaceDeclaration(ParseName(testNamespace))
                .AddMembers(testClass);

            var usings = new List<UsingDirectiveSyntax>
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.Collections.Generic")),
                UsingDirective(ParseName("System.Linq")),
                UsingDirective(ParseName("System.Text")),
                UsingDirective(ParseName("NUnit.Framework")),
                UsingDirective(ParseName("Moq")),
            };

            if (namespaceName != null)
            {
                usings.Add(UsingDirective(ParseName(namespaceName)));
            }

            var compilationUnit = CompilationUnit()
                .AddUsings(usings.ToArray())
                .AddMembers(namespaceDecl)
                .NormalizeWhitespace();

            result.Add(new TestClassInfo(testClassName + ".cs", compilationUnit.ToFullString()));
        }

        return result;
    }

    private static string? GetNamespace(ClassDeclarationSyntax classDecl)
    {
        var parent = classDecl.Parent;
        while (parent != null)
        {
            if (parent is NamespaceDeclarationSyntax ns)
                return ns.Name.ToString();
            if (parent is FileScopedNamespaceDeclarationSyntax fns)
                return fns.Name.ToString();
            parent = parent.Parent;
        }
        return null;
    }

    private static List<string> ResolveMethodNames(List<MethodDeclarationSyntax> methods)
    {
        var nameCounts = new Dictionary<string, int>();
        var result = new List<string>();

        foreach (var method in methods)
        {
            var name = method.Identifier.Text;
            if (!nameCounts.ContainsKey(name))
                nameCounts[name] = 0;
            nameCounts[name]++;
        }

        var nameIndices = new Dictionary<string, int>();

        foreach (var method in methods)
        {
            var name = method.Identifier.Text;
            if (nameCounts[name] > 1)
            {
                if (!nameIndices.ContainsKey(name))
                    nameIndices[name] = 1;
                result.Add(name + nameIndices[name]++ + "Test");
            }
            else
            {
                result.Add(name + "Test");
            }
        }

        return result;
    }

    private static string GetDefaultValueExpression(string typeName)
    {
        if (DefaultValues.TryGetValue(typeName, out var val))
            return val;
        if (typeName.StartsWith("I") && typeName.Length > 1 && char.IsUpper(typeName[1]))
            return "null";
        return "null";
    }

    private static ConstructorAnalysis AnalyzeConstructor(ClassDeclarationSyntax classDecl)
    {
        var constructors = classDecl.Members.OfType<ConstructorDeclarationSyntax>()
            .Where(c => c.Modifiers.Any(SyntaxKind.PublicKeyword))
            .ToList();

        if (constructors.Count == 0)
            return new ConstructorAnalysis();

        var ctor = constructors.OrderByDescending(c => c.ParameterList.Parameters.Count).First();
        var allParams = new List<ParameterInfo>();
        var interfaceDeps = new List<DependencyInfo>();

        foreach (var param in ctor.ParameterList.Parameters)
        {
            var typeName = param.Type?.ToString() ?? "object";
            var paramName = param.Identifier.Text;
            allParams.Add(new ParameterInfo(typeName, paramName));

            if (typeName.StartsWith("I") && typeName.Length > 1 && char.IsUpper(typeName[1]))
            {
                var fieldName = "_" + char.ToLower(paramName[0]) + paramName.Substring(1);
                interfaceDeps.Add(new DependencyInfo(typeName, paramName, fieldName));
            }
        }

        return new ConstructorAnalysis(allParams, interfaceDeps);
    }

    private class ConstructorAnalysis
    {
        public List<ParameterInfo> AllParameters { get; }
        public List<DependencyInfo> InterfaceDependencies { get; }

        public ConstructorAnalysis()
        {
            AllParameters = new List<ParameterInfo>();
            InterfaceDependencies = new List<DependencyInfo>();
        }

        public ConstructorAnalysis(List<ParameterInfo> allParams, List<DependencyInfo> deps)
        {
            AllParameters = allParams;
            InterfaceDependencies = deps;
        }
    }

    private class ParameterInfo
    {
        public string Type { get; }
        public string Name { get; }

        public ParameterInfo(string type, string name)
        {
            Type = type;
            Name = name;
        }
    }

    private class DependencyInfo
    {
        public string Type { get; }
        public string ParameterName { get; }
        public string FieldName { get; }

        public DependencyInfo(string type, string parameterName, string fieldName)
        {
            Type = type;
            ParameterName = parameterName;
            FieldName = fieldName;
        }
    }
}
