using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using MyCode;

namespace MyCode.Tests
{
    [TestFixture]
    public class MyClassTests
    {
        private MyClass _myClassUnderTest;
        private Mock<IDependency> _dependency;
        [SetUp]
        public void SetUp()
        {
            _dependency = new Mock<IDependency>();
            _myClassUnderTest = new MyClass(_dependency.Object);
        }

        [Test]
        public void FirstMethodTest()
        {
            _myClassUnderTest.FirstMethod();
            Assert.Fail("autogenerated");
        }

        [Test]
        public void SecondMethodTest()
        {
            _myClassUnderTest.SecondMethod();
            Assert.Fail("autogenerated");
        }

        [Test]
        public void ThirdMethod1Test()
        {
            int a = 0;
            _myClassUnderTest.ThirdMethod(a);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void ThirdMethod2Test()
        {
            double a = 0.0;
            _myClassUnderTest.ThirdMethod(a);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void CalculateTest()
        {
            int number = 0;
            string s = "";
            int actual = _myClassUnderTest.Calculate(number, s);
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}